import os
from dotenv import load_dotenv
from google.generativeai import GenerativeModel, configure

load_dotenv()

configure(api_key=os.getenv("GOOGLE_API_KEY"))

model = GenerativeModel("gemini-2.5-flash")

def gemini_response(prompt: str):
    """
    Generate a response from the Gemini model based on the provided prompt.
    
    Args:
        prompt (str): The user input or query.

    Returns:
        str: The text output generated by the model.
    """

    result = model.generate_content(prompt)

    return result.text